name: CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    name: 'Build Website'
    runs-on: ubuntu-latest
    steps:
      - uses: browser-actions/setup-chrome@v1
        with:
          chrome-version: 1198101
        id: setup-chrome
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          lfs: true
      - name: Load dependency cache
        uses: actions/cache@v3
        with:
          path: |
            **/node_modules
            /home/runner/.cache/puppeteer
          key: ${{ runner.os }}-dependencies-v1-${{ hashFiles('yarn.lock') }}
      - name: Load site cache
        uses: actions/cache@v3
        with:
          path: |
            **/dist
          key: ${{ runner.os }}-site-v1-${{ hashFiles('yarn.lock') }}-${{ github.run_number }}
      - name: Install fonts
        run: |
          sudo apt update
          echo ttf-mscorefonts-installer msttcorefonts/accepted-mscorefonts-eula select true | sudo debconf-set-selections
          sudo apt-get install ttf-mscorefonts-installer
      - uses: actions/setup-node@v2
        with:
          node-version: '22'
      - name: Installing Dependencies
        run: |
          yarn install
      - name: Build site
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN_GLOBAL }}
        run: |
          npm run build
          npm run build:docs

  deploy_github:
    needs:
      - build
    name: 'Deploy to Github Pages'
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Load dependency cache
        uses: actions/cache@v3
        with:
          path: |
            **/node_modules
            /home/runner/.cache/puppeteer
          key: ${{ runner.os }}-dependencies-v1-${{ hashFiles('yarn.lock') }}
      - name: Load site cache
        uses: actions/cache@v3
        with:
          path: |
            **/dist
          key: ${{ runner.os }}-site-v1-${{ hashFiles('yarn.lock') }}-${{ github.run_number }}
      - name: Deploy site to GitHub
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
      - name: Status check
        uses: Sibz/github-status-action@v1
        with:
          authToken: ${{ secrets.GITHUB_TOKEN }}
          context: Github Pages preview
          state: success
          target_url: https://sembeacon.github.io/sembeacon.org/